### ISSUE TITLE
diagnostics for MCMC chains

### ISSUE THREAD

**Issue by vladpetyuk** [tian52/2016InternProject#1]
please add 3 following diagnostics of MCMC sampling
1. burn-in
2. autocorrelation
3. mixin. Gelman-Rubin criterion.

**Comment by tian52** [comment]
All three diagnostics are added:
1, burn-in: add "n.burnin" option to "update" commend.
2, autocorrelation: done by "autocorr", "autocorr.diag", and "autocorr.plot".
3, Gelman-Rubin criterion: done by "gelman.diag" and "gelman.plot".
