### ISSUE TITLE
Shrink variation estimates

### ISSUE THREAD

**Issue by tian52** [tian52/2016InternProject#3]
I cannot use the same uniform distribution Unif(0, 10) to get the upper and the lower bound of the uniform distribution that are used to get sigma. Once I change one of the distributions to Unif(0, 9.99), the code works well. 
The code is located at line 37 and 38. [Code](https://github.com/tian52/2016InternProject/blob/master/Model4/banova_multiple_testing_mdim_YT4.R)

**Comment by vladpetyuk** [comment]
updated to 
1) defining left (min) value
2) width of the uniform dist window
3) right = left + width
